// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace LittleGame_SmartestMen
{
    [default_interface]
    runtimeclass MyContent : Microsoft.UI.Xaml.Controls.Page
    {
        MyContent();
        Int32 MyProperty;
    }
}
